# Generated by Django 4.0.1 on 2022-03-24 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0003_alter_order_destination_alter_order_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_profile_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.userprofileinfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='warehouse',
        ),
        migrations.AlterField(
            model_name='movement',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_destination', to='my_app.userprofileinfo'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_source', to='my_app.userprofileinfo'),
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.DeleteModel(
            name='WarehouseProduct',
        ),
    ]
