# Generated by Django 4.0.1 on 2022-03-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_userprofileinfoproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sequence',
            field=models.IntegerField(max_length=20),
        ),
    ]
