# Generated by Django 4.0.1 on 2022-03-27 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_movement_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_destination', to='my_app.userprofileinfo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sequence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_source', to='my_app.userprofileinfo'),
        ),
    ]
