# Generated by Django 4.0.1 on 2022-03-27 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_order_destination_alter_order_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_order_destination', to='my_app.userprofileinfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.product')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_order_source', to='my_app.userprofileinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SearchMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_movement_destination', to='my_app.userprofileinfo')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.product')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_movement_source', to='my_app.userprofileinfo')),
            ],
        ),
    ]
