# Generated by Django 4.0.1 on 2022-03-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_searchorder_searchmovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchmovement',
            name='order',
        ),
        migrations.AddField(
            model_name='searchmovement',
            name='sequence',
            field=models.IntegerField(null=True),
        ),
    ]
